//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dscf.SettleMents.Web.DscfBIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuEntity", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class MenuEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Icon {
            get {
                return this.IconField;
            }
            set {
                if ((object.ReferenceEquals(this.IconField, value) != true)) {
                    this.IconField = value;
                    this.RaisePropertyChanged("Icon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionEntity", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class PermissionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsPagePermissionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPagePermission {
            get {
                return this.IsPagePermissionField;
            }
            set {
                if ((this.IsPagePermissionField.Equals(value) != true)) {
                    this.IsPagePermissionField = value;
                    this.RaisePropertyChanged("IsPagePermission");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperaterEntity", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class OperaterEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dscf.SettleMents.Web.DscfBIService.DepartmentEntity DepartmentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dscf.SettleMents.Web.DscfBIService.RoleEntity[] RoleListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeiXinField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dscf.SettleMents.Web.DscfBIService.DepartmentEntity DepartmentInfo {
            get {
                return this.DepartmentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentInfoField, value) != true)) {
                    this.DepartmentInfoField = value;
                    this.RaisePropertyChanged("DepartmentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EntryDate {
            get {
                return this.EntryDateField;
            }
            set {
                if ((this.EntryDateField.Equals(value) != true)) {
                    this.EntryDateField = value;
                    this.RaisePropertyChanged("EntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCard {
            get {
                return this.IDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardField, value) != true)) {
                    this.IDCardField = value;
                    this.RaisePropertyChanged("IDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dscf.SettleMents.Web.DscfBIService.RoleEntity[] RoleList {
            get {
                return this.RoleListField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleListField, value) != true)) {
                    this.RoleListField = value;
                    this.RaisePropertyChanged("RoleList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WeiXin {
            get {
                return this.WeiXinField;
            }
            set {
                if ((object.ReferenceEquals(this.WeiXinField, value) != true)) {
                    this.WeiXinField = value;
                    this.RaisePropertyChanged("WeiXin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentEntity", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class DepartmentEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerServicePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EarlyRepayPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevolvingLoanPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerServicePhone {
            get {
                return this.CustomerServicePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerServicePhoneField, value) != true)) {
                    this.CustomerServicePhoneField = value;
                    this.RaisePropertyChanged("CustomerServicePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EarlyRepayPhone {
            get {
                return this.EarlyRepayPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.EarlyRepayPhoneField, value) != true)) {
                    this.EarlyRepayPhoneField = value;
                    this.RaisePropertyChanged("EarlyRepayPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevolvingLoanPhone {
            get {
                return this.RevolvingLoanPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.RevolvingLoanPhoneField, value) != true)) {
                    this.RevolvingLoanPhoneField = value;
                    this.RaisePropertyChanged("RevolvingLoanPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignAddress {
            get {
                return this.SignAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SignAddressField, value) != true)) {
                    this.SignAddressField = value;
                    this.RaisePropertyChanged("SignAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignCity {
            get {
                return this.SignCityField;
            }
            set {
                if ((object.ReferenceEquals(this.SignCityField, value) != true)) {
                    this.SignCityField = value;
                    this.RaisePropertyChanged("SignCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignZipCode {
            get {
                return this.SignZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SignZipCodeField, value) != true)) {
                    this.SignZipCodeField = value;
                    this.RaisePropertyChanged("SignZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleEntity", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class RoleEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthOptRequest", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class AuthOptRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAjaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptCookieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlatformIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScreenResolutionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessPath {
            get {
                return this.AccessPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessPathField, value) != true)) {
                    this.AccessPathField = value;
                    this.RaisePropertyChanged("AccessPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Browser {
            get {
                return this.BrowserField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowserField, value) != true)) {
                    this.BrowserField = value;
                    this.RaisePropertyChanged("Browser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAjax {
            get {
                return this.IsAjaxField;
            }
            set {
                if ((this.IsAjaxField.Equals(value) != true)) {
                    this.IsAjaxField = value;
                    this.RaisePropertyChanged("IsAjax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OptCookie {
            get {
                return this.OptCookieField;
            }
            set {
                if ((object.ReferenceEquals(this.OptCookieField, value) != true)) {
                    this.OptCookieField = value;
                    this.RaisePropertyChanged("OptCookie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlatformId {
            get {
                return this.PlatformIdField;
            }
            set {
                if ((this.PlatformIdField.Equals(value) != true)) {
                    this.PlatformIdField = value;
                    this.RaisePropertyChanged("PlatformId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScreenResolution {
            get {
                return this.ScreenResolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.ScreenResolutionField, value) != true)) {
                    this.ScreenResolutionField = value;
                    this.RaisePropertyChanged("ScreenResolution");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthResult", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class AuthResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dscf.SettleMents.Web.DscfBIService.EnumAuthStatus AuthStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dscf.SettleMents.Web.DscfBIService.EnumAuthStatus AuthStatus {
            get {
                return this.AuthStatusField;
            }
            set {
                if ((this.AuthStatusField.Equals(value) != true)) {
                    this.AuthStatusField = value;
                    this.RaisePropertyChanged("AuthStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumAuthStatus", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    public enum EnumAuthStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoLogin = 300,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgainLogin = 350,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPermission = 400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DecryptError = 500,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatformEntity", Namespace="http://schemas.datacontract.org/2004/07/Dscf.BusinessIntegrate.Contract")]
    [System.SerializableAttribute()]
    public partial class PlatformEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PlatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlatformNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeUrl {
            get {
                return this.HomeUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeUrlField, value) != true)) {
                    this.HomeUrlField = value;
                    this.RaisePropertyChanged("HomeUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlatId {
            get {
                return this.PlatIdField;
            }
            set {
                if ((this.PlatIdField.Equals(value) != true)) {
                    this.PlatIdField = value;
                    this.RaisePropertyChanged("PlatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlatformName {
            get {
                return this.PlatformNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformNameField, value) != true)) {
                    this.PlatformNameField = value;
                    this.RaisePropertyChanged("PlatformName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DscfBIService.IDscfBIServerConract")]
    public interface IDscfBIServerConract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/GetPlatformMenuListByOptId", ReplyAction="http://tempuri.org/IDscfBIServerConract/GetPlatformMenuListByOptIdResponse")]
        Dscf.SettleMents.Web.DscfBIService.MenuEntity[] GetPlatformMenuListByOptId(string optCookie, int platformId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/GetPlatformMenuListByOptId", ReplyAction="http://tempuri.org/IDscfBIServerConract/GetPlatformMenuListByOptIdResponse")]
        System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.MenuEntity[]> GetPlatformMenuListByOptIdAsync(string optCookie, int platformId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/GetPlatformPermissionListByOptId", ReplyAction="http://tempuri.org/IDscfBIServerConract/GetPlatformPermissionListByOptIdResponse")]
        Dscf.SettleMents.Web.DscfBIService.PermissionEntity[] GetPlatformPermissionListByOptId(string optCookie, int platformId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/GetPlatformPermissionListByOptId", ReplyAction="http://tempuri.org/IDscfBIServerConract/GetPlatformPermissionListByOptIdResponse")]
        System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.PermissionEntity[]> GetPlatformPermissionListByOptIdAsync(string optCookie, int platformId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/GetOperaterInfoByCookie", ReplyAction="http://tempuri.org/IDscfBIServerConract/GetOperaterInfoByCookieResponse")]
        Dscf.SettleMents.Web.DscfBIService.OperaterEntity GetOperaterInfoByCookie(string optCookie, int platformId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/GetOperaterInfoByCookie", ReplyAction="http://tempuri.org/IDscfBIServerConract/GetOperaterInfoByCookieResponse")]
        System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.OperaterEntity> GetOperaterInfoByCookieAsync(string optCookie, int platformId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/AuthOperaterIsLicit", ReplyAction="http://tempuri.org/IDscfBIServerConract/AuthOperaterIsLicitResponse")]
        Dscf.SettleMents.Web.DscfBIService.AuthResult AuthOperaterIsLicit(Dscf.SettleMents.Web.DscfBIService.AuthOptRequest authOptRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/AuthOperaterIsLicit", ReplyAction="http://tempuri.org/IDscfBIServerConract/AuthOperaterIsLicitResponse")]
        System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.AuthResult> AuthOperaterIsLicitAsync(Dscf.SettleMents.Web.DscfBIService.AuthOptRequest authOptRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/SelectAccessPlatformListByCookie", ReplyAction="http://tempuri.org/IDscfBIServerConract/SelectAccessPlatformListByCookieResponse")]
        Dscf.SettleMents.Web.DscfBIService.PlatformEntity[] SelectAccessPlatformListByCookie(string optCookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/SelectAccessPlatformListByCookie", ReplyAction="http://tempuri.org/IDscfBIServerConract/SelectAccessPlatformListByCookieResponse")]
        System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.PlatformEntity[]> SelectAccessPlatformListByCookieAsync(string optCookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/SeleOperaterListByCookie", ReplyAction="http://tempuri.org/IDscfBIServerConract/SeleOperaterListByCookieResponse")]
        Dscf.SettleMents.Web.DscfBIService.OperaterEntity[] SeleOperaterListByCookie(string optCookie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDscfBIServerConract/SeleOperaterListByCookie", ReplyAction="http://tempuri.org/IDscfBIServerConract/SeleOperaterListByCookieResponse")]
        System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.OperaterEntity[]> SeleOperaterListByCookieAsync(string optCookie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDscfBIServerConractChannel : Dscf.SettleMents.Web.DscfBIService.IDscfBIServerConract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DscfBIServerConractClient : System.ServiceModel.ClientBase<Dscf.SettleMents.Web.DscfBIService.IDscfBIServerConract>, Dscf.SettleMents.Web.DscfBIService.IDscfBIServerConract {
        
        public DscfBIServerConractClient() {
        }
        
        public DscfBIServerConractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DscfBIServerConractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DscfBIServerConractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DscfBIServerConractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dscf.SettleMents.Web.DscfBIService.MenuEntity[] GetPlatformMenuListByOptId(string optCookie, int platformId) {
            return base.Channel.GetPlatformMenuListByOptId(optCookie, platformId);
        }
        
        public System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.MenuEntity[]> GetPlatformMenuListByOptIdAsync(string optCookie, int platformId) {
            return base.Channel.GetPlatformMenuListByOptIdAsync(optCookie, platformId);
        }
        
        public Dscf.SettleMents.Web.DscfBIService.PermissionEntity[] GetPlatformPermissionListByOptId(string optCookie, int platformId) {
            return base.Channel.GetPlatformPermissionListByOptId(optCookie, platformId);
        }
        
        public System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.PermissionEntity[]> GetPlatformPermissionListByOptIdAsync(string optCookie, int platformId) {
            return base.Channel.GetPlatformPermissionListByOptIdAsync(optCookie, platformId);
        }
        
        public Dscf.SettleMents.Web.DscfBIService.OperaterEntity GetOperaterInfoByCookie(string optCookie, int platformId) {
            return base.Channel.GetOperaterInfoByCookie(optCookie, platformId);
        }
        
        public System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.OperaterEntity> GetOperaterInfoByCookieAsync(string optCookie, int platformId) {
            return base.Channel.GetOperaterInfoByCookieAsync(optCookie, platformId);
        }
        
        public Dscf.SettleMents.Web.DscfBIService.AuthResult AuthOperaterIsLicit(Dscf.SettleMents.Web.DscfBIService.AuthOptRequest authOptRequest) {
            return base.Channel.AuthOperaterIsLicit(authOptRequest);
        }
        
        public System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.AuthResult> AuthOperaterIsLicitAsync(Dscf.SettleMents.Web.DscfBIService.AuthOptRequest authOptRequest) {
            return base.Channel.AuthOperaterIsLicitAsync(authOptRequest);
        }
        
        public Dscf.SettleMents.Web.DscfBIService.PlatformEntity[] SelectAccessPlatformListByCookie(string optCookie) {
            return base.Channel.SelectAccessPlatformListByCookie(optCookie);
        }
        
        public System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.PlatformEntity[]> SelectAccessPlatformListByCookieAsync(string optCookie) {
            return base.Channel.SelectAccessPlatformListByCookieAsync(optCookie);
        }
        
        public Dscf.SettleMents.Web.DscfBIService.OperaterEntity[] SeleOperaterListByCookie(string optCookie) {
            return base.Channel.SeleOperaterListByCookie(optCookie);
        }
        
        public System.Threading.Tasks.Task<Dscf.SettleMents.Web.DscfBIService.OperaterEntity[]> SeleOperaterListByCookieAsync(string optCookie) {
            return base.Channel.SeleOperaterListByCookieAsync(optCookie);
        }
    }
}
