//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dscf.PostLoan.AuthCenterBLL.DscfACService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepartmentInfoDto", Namespace="http://schemas.datacontract.org/2004/07/Dscf.AuthCenter.Dto")]
    [System.SerializableAttribute()]
    public partial class DepartmentInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignCityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignAddress {
            get {
                return this.SignAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.SignAddressField, value) != true)) {
                    this.SignAddressField = value;
                    this.RaisePropertyChanged("SignAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignCity {
            get {
                return this.SignCityField;
            }
            set {
                if ((object.ReferenceEquals(this.SignCityField, value) != true)) {
                    this.SignCityField = value;
                    this.RaisePropertyChanged("SignCity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperaterInfoDto", Namespace="http://schemas.datacontract.org/2004/07/Dscf.AuthCenter.Dto")]
    [System.SerializableAttribute()]
    public partial class OperaterInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CollectionTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] RoleIdListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto[] SupportDeptListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CollectionTypeId {
            get {
                return this.CollectionTypeIdField;
            }
            set {
                if ((this.CollectionTypeIdField.Equals(value) != true)) {
                    this.CollectionTypeIdField = value;
                    this.RaisePropertyChanged("CollectionTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionTypeName {
            get {
                return this.CollectionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionTypeNameField, value) != true)) {
                    this.CollectionTypeNameField = value;
                    this.RaisePropertyChanged("CollectionTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCard {
            get {
                return this.IDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardField, value) != true)) {
                    this.IDCardField = value;
                    this.RaisePropertyChanged("IDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] RoleIdList {
            get {
                return this.RoleIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleIdListField, value) != true)) {
                    this.RoleIdListField = value;
                    this.RaisePropertyChanged("RoleIdList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto[] SupportDeptList {
            get {
                return this.SupportDeptListField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportDeptListField, value) != true)) {
                    this.SupportDeptListField = value;
                    this.RaisePropertyChanged("SupportDeptList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OptCityDto", Namespace="http://schemas.datacontract.org/2004/07/Dscf.AuthCenter.Dto")]
    [System.SerializableAttribute()]
    public partial class OptCityDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int>[] SupportDeptListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int>[] SupportDeptList {
            get {
                return this.SupportDeptListField;
            }
            set {
                if ((object.ReferenceEquals(this.SupportDeptListField, value) != true)) {
                    this.SupportDeptListField = value;
                    this.RaisePropertyChanged("SupportDeptList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DictionaryDto", Namespace="http://schemas.datacontract.org/2004/07/Dscf.AuthCenter.Dto")]
    [System.SerializableAttribute()]
    public partial class DictionaryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DictIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DictMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DictValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DictId {
            get {
                return this.DictIdField;
            }
            set {
                if ((this.DictIdField.Equals(value) != true)) {
                    this.DictIdField = value;
                    this.RaisePropertyChanged("DictId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DictKey {
            get {
                return this.DictKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.DictKeyField, value) != true)) {
                    this.DictKeyField = value;
                    this.RaisePropertyChanged("DictKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DictMemo {
            get {
                return this.DictMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.DictMemoField, value) != true)) {
                    this.DictMemoField = value;
                    this.RaisePropertyChanged("DictMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DictValue {
            get {
                return this.DictValueField;
            }
            set {
                if ((this.DictValueField.Equals(value) != true)) {
                    this.DictValueField = value;
                    this.RaisePropertyChanged("DictValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Parent {
            get {
                return this.ParentField;
            }
            set {
                if ((this.ParentField.Equals(value) != true)) {
                    this.ParentField = value;
                    this.RaisePropertyChanged("Parent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sort {
            get {
                return this.SortField;
            }
            set {
                if ((this.SortField.Equals(value) != true)) {
                    this.SortField = value;
                    this.RaisePropertyChanged("Sort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DscfACService.IAuthCenterContract")]
    public interface IAuthCenterContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetRoleIdsById", ReplyAction="http://tempuri.org/IAuthCenterContract/GetRoleIdsByIdResponse")]
        int[] GetRoleIdsById(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetRoleIdsById", ReplyAction="http://tempuri.org/IAuthCenterContract/GetRoleIdsByIdResponse")]
        System.Threading.Tasks.Task<int[]> GetRoleIdsByIdAsync(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDeptIdsById", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDeptIdsByIdResponse")]
        int[] GetDeptIdsById(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDeptIdsById", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDeptIdsByIdResponse")]
        System.Threading.Tasks.Task<int[]> GetDeptIdsByIdAsync(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDeptByDeptID", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDeptByDeptIDResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto GetDeptByDeptID(int deptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDeptByDeptID", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDeptByDeptIDResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto> GetDeptByDeptIDAsync(int deptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDeptSignSitiesById", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDeptSignSitiesByIdResponse")]
        string[] GetDeptSignSitiesById(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDeptSignSitiesById", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDeptSignSitiesByIdResponse")]
        System.Threading.Tasks.Task<string[]> GetDeptSignSitiesByIdAsync(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetCollectorListByRole", ReplyAction="http://tempuri.org/IAuthCenterContract/GetCollectorListByRoleResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[] GetCollectorListByRole(int[] roleIdArr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetCollectorListByRole", ReplyAction="http://tempuri.org/IAuthCenterContract/GetCollectorListByRoleResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[]> GetCollectorListByRoleAsync(int[] roleIdArr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetChildDeptListByDeptID", ReplyAction="http://tempuri.org/IAuthCenterContract/GetChildDeptListByDeptIDResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto[] GetChildDeptListByDeptID(int parentDeptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetChildDeptListByDeptID", ReplyAction="http://tempuri.org/IAuthCenterContract/GetChildDeptListByDeptIDResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto[]> GetChildDeptListByDeptIDAsync(int parentDeptID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/UpdateOptCollectionType", ReplyAction="http://tempuri.org/IAuthCenterContract/UpdateOptCollectionTypeResponse")]
        bool UpdateOptCollectionType(int optId, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/UpdateOptCollectionType", ReplyAction="http://tempuri.org/IAuthCenterContract/UpdateOptCollectionTypeResponse")]
        System.Threading.Tasks.Task<bool> UpdateOptCollectionTypeAsync(int optId, int type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetOperaterInfoByID", ReplyAction="http://tempuri.org/IAuthCenterContract/GetOperaterInfoByIDResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto GetOperaterInfoByID(int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetOperaterInfoByID", ReplyAction="http://tempuri.org/IAuthCenterContract/GetOperaterInfoByIDResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto> GetOperaterInfoByIDAsync(int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetOperaterInfoList", ReplyAction="http://tempuri.org/IAuthCenterContract/GetOperaterInfoListResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[] GetOperaterInfoList(int[] optIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetOperaterInfoList", ReplyAction="http://tempuri.org/IAuthCenterContract/GetOperaterInfoListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[]> GetOperaterInfoListAsync(int[] optIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetOperaterInfoLists", ReplyAction="http://tempuri.org/IAuthCenterContract/GetOperaterInfoListsResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[] GetOperaterInfoLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetOperaterInfoLists", ReplyAction="http://tempuri.org/IAuthCenterContract/GetOperaterInfoListsResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[]> GetOperaterInfoListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetCollectorSupportCityList", ReplyAction="http://tempuri.org/IAuthCenterContract/GetCollectorSupportCityListResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.OptCityDto[] GetCollectorSupportCityList(int roleId, int typeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetCollectorSupportCityList", ReplyAction="http://tempuri.org/IAuthCenterContract/GetCollectorSupportCityListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OptCityDto[]> GetCollectorSupportCityListAsync(int roleId, int typeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDictListByKey", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDictListByKeyResponse")]
        Dscf.PostLoan.AuthCenterBLL.DscfACService.DictionaryDto[] GetDictListByKey(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetDictListByKey", ReplyAction="http://tempuri.org/IAuthCenterContract/GetDictListByKeyResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.DictionaryDto[]> GetDictListByKeyAsync(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetRemindNameByType", ReplyAction="http://tempuri.org/IAuthCenterContract/GetRemindNameByTypeResponse")]
        string GetRemindNameByType(string dictKey, System.Nullable<int> type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/GetRemindNameByType", ReplyAction="http://tempuri.org/IAuthCenterContract/GetRemindNameByTypeResponse")]
        System.Threading.Tasks.Task<string> GetRemindNameByTypeAsync(string dictKey, System.Nullable<int> type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/UpdateCollectorSupportCityList", ReplyAction="http://tempuri.org/IAuthCenterContract/UpdateCollectorSupportCityListResponse")]
        bool UpdateCollectorSupportCityList(int optId, int[] deptIdList, int sourceType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthCenterContract/UpdateCollectorSupportCityList", ReplyAction="http://tempuri.org/IAuthCenterContract/UpdateCollectorSupportCityListResponse")]
        System.Threading.Tasks.Task<bool> UpdateCollectorSupportCityListAsync(int optId, int[] deptIdList, int sourceType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthCenterContractChannel : Dscf.PostLoan.AuthCenterBLL.DscfACService.IAuthCenterContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthCenterContractClient : System.ServiceModel.ClientBase<Dscf.PostLoan.AuthCenterBLL.DscfACService.IAuthCenterContract>, Dscf.PostLoan.AuthCenterBLL.DscfACService.IAuthCenterContract {
        
        public AuthCenterContractClient() {
        }
        
        public AuthCenterContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthCenterContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthCenterContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthCenterContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetRoleIdsById(int key) {
            return base.Channel.GetRoleIdsById(key);
        }
        
        public System.Threading.Tasks.Task<int[]> GetRoleIdsByIdAsync(int key) {
            return base.Channel.GetRoleIdsByIdAsync(key);
        }
        
        public int[] GetDeptIdsById(int key) {
            return base.Channel.GetDeptIdsById(key);
        }
        
        public System.Threading.Tasks.Task<int[]> GetDeptIdsByIdAsync(int key) {
            return base.Channel.GetDeptIdsByIdAsync(key);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto GetDeptByDeptID(int deptID) {
            return base.Channel.GetDeptByDeptID(deptID);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto> GetDeptByDeptIDAsync(int deptID) {
            return base.Channel.GetDeptByDeptIDAsync(deptID);
        }
        
        public string[] GetDeptSignSitiesById(int key) {
            return base.Channel.GetDeptSignSitiesById(key);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDeptSignSitiesByIdAsync(int key) {
            return base.Channel.GetDeptSignSitiesByIdAsync(key);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[] GetCollectorListByRole(int[] roleIdArr) {
            return base.Channel.GetCollectorListByRole(roleIdArr);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[]> GetCollectorListByRoleAsync(int[] roleIdArr) {
            return base.Channel.GetCollectorListByRoleAsync(roleIdArr);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto[] GetChildDeptListByDeptID(int parentDeptID) {
            return base.Channel.GetChildDeptListByDeptID(parentDeptID);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.DepartmentInfoDto[]> GetChildDeptListByDeptIDAsync(int parentDeptID) {
            return base.Channel.GetChildDeptListByDeptIDAsync(parentDeptID);
        }
        
        public bool UpdateOptCollectionType(int optId, int type) {
            return base.Channel.UpdateOptCollectionType(optId, type);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateOptCollectionTypeAsync(int optId, int type) {
            return base.Channel.UpdateOptCollectionTypeAsync(optId, type);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto GetOperaterInfoByID(int optId) {
            return base.Channel.GetOperaterInfoByID(optId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto> GetOperaterInfoByIDAsync(int optId) {
            return base.Channel.GetOperaterInfoByIDAsync(optId);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[] GetOperaterInfoList(int[] optIdList) {
            return base.Channel.GetOperaterInfoList(optIdList);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[]> GetOperaterInfoListAsync(int[] optIdList) {
            return base.Channel.GetOperaterInfoListAsync(optIdList);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[] GetOperaterInfoLists() {
            return base.Channel.GetOperaterInfoLists();
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OperaterInfoDto[]> GetOperaterInfoListsAsync() {
            return base.Channel.GetOperaterInfoListsAsync();
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.OptCityDto[] GetCollectorSupportCityList(int roleId, int typeId) {
            return base.Channel.GetCollectorSupportCityList(roleId, typeId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.OptCityDto[]> GetCollectorSupportCityListAsync(int roleId, int typeId) {
            return base.Channel.GetCollectorSupportCityListAsync(roleId, typeId);
        }
        
        public Dscf.PostLoan.AuthCenterBLL.DscfACService.DictionaryDto[] GetDictListByKey(string key) {
            return base.Channel.GetDictListByKey(key);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.AuthCenterBLL.DscfACService.DictionaryDto[]> GetDictListByKeyAsync(string key) {
            return base.Channel.GetDictListByKeyAsync(key);
        }
        
        public string GetRemindNameByType(string dictKey, System.Nullable<int> type) {
            return base.Channel.GetRemindNameByType(dictKey, type);
        }
        
        public System.Threading.Tasks.Task<string> GetRemindNameByTypeAsync(string dictKey, System.Nullable<int> type) {
            return base.Channel.GetRemindNameByTypeAsync(dictKey, type);
        }
        
        public bool UpdateCollectorSupportCityList(int optId, int[] deptIdList, int sourceType) {
            return base.Channel.UpdateCollectorSupportCityList(optId, deptIdList, sourceType);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCollectorSupportCityListAsync(int optId, int[] deptIdList, int sourceType) {
            return base.Channel.UpdateCollectorSupportCityListAsync(optId, deptIdList, sourceType);
        }
    }
}
