//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dscf.PostLoan.Web.DscfCarLoanService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DscfCarLoanService.ICarLoanContract")]
    public interface ICarLoanContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/QueryUserInfoList", ReplyAction="http://tempuri.org/ICarLoanContract/QueryUserInfoListResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarUserInfoDto[] QueryUserInfoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/QueryUserInfoList", ReplyAction="http://tempuri.org/ICarLoanContract/QueryUserInfoListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarUserInfoDto[]> QueryUserInfoListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageCarLoanBatchDeductList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageCarLoanBatchDeductListResponse")]
        Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto> GetPageCarLoanBatchDeductList(int pageNum, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageCarLoanBatchDeductList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageCarLoanBatchDeductListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto>> GetPageCarLoanBatchDeductListAsync(int pageNum, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatus", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatusResponse")]
        bool UpdateOrderCollectStatus(int orderId, int collectStatus, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatus", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatusResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderCollectStatusAsync(int orderId, int collectStatus, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatusBatch", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatusBatchResponse")]
        bool UpdateOrderCollectStatusBatch(int[] orderIds, int collectStatus, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatusBatch", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateOrderCollectStatusBatchResponse")]
        System.Threading.Tasks.Task<bool> UpdateOrderCollectStatusBatchAsync(int[] orderIds, int collectStatus, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/SelectLoanProductOrderList", ReplyAction="http://tempuri.org/ICarLoanContract/SelectLoanProductOrderListResponse")]
        Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto> SelectLoanProductOrderList(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanSearchaRequest loanSearchaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/SelectLoanProductOrderList", ReplyAction="http://tempuri.org/ICarLoanContract/SelectLoanProductOrderListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto>> SelectLoanProductOrderListAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanSearchaRequest loanSearchaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductOrderInfoByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductOrderInfoByOrderIdResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto GetLoanProductOrderInfoByOrderId(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductOrderInfoByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductOrderInfoByOrderIdResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto> GetLoanProductOrderInfoByOrderIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductExtensionOrderByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductExtensionOrderByOrderIdResponse" +
            "")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductExtensionOrderDto GetLoanProductExtensionOrderByOrderId(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductExtensionOrderByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductExtensionOrderByOrderIdResponse" +
            "")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductExtensionOrderDto> GetLoanProductExtensionOrderByOrderIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetRepayRemindList", ReplyAction="http://tempuri.org/ICarLoanContract/GetRepayRemindListResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto[] GetRepayRemindList(string RepayIdArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetRepayRemindList", ReplyAction="http://tempuri.org/ICarLoanContract/GetRepayRemindListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto[]> GetRepayRemindListAsync(string RepayIdArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageOverdueList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageOverdueListResponse")]
        Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto> GetPageOverdueList(int pageNum, int pageSize, System.Nullable<bool> isLongLoan, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageOverdueList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageOverdueListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto>> GetPageOverdueListAsync(int pageNum, int pageSize, System.Nullable<bool> isLongLoan, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductOrderDetail", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductOrderDetailResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanOrderDetailDto GetLoanProductOrderDetail(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductOrderDetail", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductOrderDetailResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanOrderDetailDto> GetLoanProductOrderDetailAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductOrderSingleById", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductOrderSingleByIdResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto GetLoanProductOrderSingleById(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanProductOrderSingleById", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanProductOrderSingleByIdResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto> GetLoanProductOrderSingleByIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateLoanProductOrder", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateLoanProductOrderResponse")]
        bool UpdateLoanProductOrder(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto orderDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateLoanProductOrder", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateLoanProductOrderResponse")]
        System.Threading.Tasks.Task<bool> UpdateLoanProductOrderAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto orderDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/EditLoanOrderReminderByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/EditLoanOrderReminderByOrderIdResponse")]
        bool EditLoanOrderReminderByOrderId(int orderId, int deptOptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/EditLoanOrderReminderByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/EditLoanOrderReminderByOrderIdResponse")]
        System.Threading.Tasks.Task<bool> EditLoanOrderReminderByOrderIdAsync(int orderId, int deptOptId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageDeductApprovalList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageDeductApprovalListResponse")]
        Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto> GetPageDeductApprovalList(int pageNum, int pageSize, int[] keyList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageDeductApprovalList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageDeductApprovalListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto>> GetPageDeductApprovalListAsync(int pageNum, int pageSize, int[] keyList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetOverdueExcelList", ReplyAction="http://tempuri.org/ICarLoanContract/GetOverdueExcelListResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueExcelDto[] GetOverdueExcelList(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.OverdueSearchRequest overdueSearchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetOverdueExcelList", ReplyAction="http://tempuri.org/ICarLoanContract/GetOverdueExcelListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueExcelDto[]> GetOverdueExcelListAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.OverdueSearchRequest overdueSearchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateMonthRepayInfo", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateMonthRepayInfoResponse")]
        bool UpdateMonthRepayInfo(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarDeductViewModelDto dto, int operaterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateMonthRepayInfo", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateMonthRepayInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdateMonthRepayInfoAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarDeductViewModelDto dto, int operaterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanMonthRepayInfoByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanMonthRepayInfoByOrderIdResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanMonthRepayDto[] GetLoanMonthRepayInfoByOrderId(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetLoanMonthRepayInfoByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/GetLoanMonthRepayInfoByOrderIdResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanMonthRepayDto[]> GetLoanMonthRepayInfoByOrderIdAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageRepayRemindList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageRepayRemindListResponse")]
        Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto> GetPageRepayRemindList(int pageNum, int pageSize, bool isLongLoan, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetPageRepayRemindList", ReplyAction="http://tempuri.org/ICarLoanContract/GetPageRepayRemindListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto>> GetPageRepayRemindListAsync(int pageNum, int pageSize, bool isLongLoan, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateRepayRemindByRepayId", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateRepayRemindByRepayIdResponse")]
        bool UpdateRepayRemindByRepayId(int repayId, int isRemind, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateRepayRemindByRepayId", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateRepayRemindByRepayIdResponse")]
        System.Threading.Tasks.Task<bool> UpdateRepayRemindByRepayIdAsync(int repayId, int isRemind, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetCarRemindDetail", ReplyAction="http://tempuri.org/ICarLoanContract/GetCarRemindDetailResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemidDetailDto GetCarRemindDetail(int orderId, int repayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetCarRemindDetail", ReplyAction="http://tempuri.org/ICarLoanContract/GetCarRemindDetailResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemidDetailDto> GetCarRemindDetailAsync(int orderId, int repayId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetIsRemindCount", ReplyAction="http://tempuri.org/ICarLoanContract/GetIsRemindCountResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarCountDto GetIsRemindCount(bool isLongLoan, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetIsRemindCount", ReplyAction="http://tempuri.org/ICarLoanContract/GetIsRemindCountResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarCountDto> GetIsRemindCountAsync(bool isLongLoan, int optId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/AddLoanExtensionApplyByDto", ReplyAction="http://tempuri.org/ICarLoanContract/AddLoanExtensionApplyByDtoResponse")]
        bool AddLoanExtensionApplyByDto(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanExtensionApplyDto carLoanExtensionApplyDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/AddLoanExtensionApplyByDto", ReplyAction="http://tempuri.org/ICarLoanContract/AddLoanExtensionApplyByDtoResponse")]
        System.Threading.Tasks.Task<bool> AddLoanExtensionApplyByDtoAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanExtensionApplyDto carLoanExtensionApplyDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetExhibitionReviewlist", ReplyAction="http://tempuri.org/ICarLoanContract/GetExhibitionReviewlistResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto[] GetExhibitionReviewlist(System.Nullable<int> orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetExhibitionReviewlist", ReplyAction="http://tempuri.org/ICarLoanContract/GetExhibitionReviewlistResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto[]> GetExhibitionReviewlistAsync(System.Nullable<int> orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/InsertExhibitionReview", ReplyAction="http://tempuri.org/ICarLoanContract/InsertExhibitionReviewResponse")]
        Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewResponse InsertExhibitionReview(Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/InsertExhibitionReview", ReplyAction="http://tempuri.org/ICarLoanContract/InsertExhibitionReviewResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewResponse> InsertExhibitionReviewAsync(Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateExhibitionReview", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateExhibitionReviewResponse")]
        Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewResponse UpdateExhibitionReview(Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateExhibitionReview", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateExhibitionReviewResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewResponse> UpdateExhibitionReviewAsync(Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/InsertImages", ReplyAction="http://tempuri.org/ICarLoanContract/InsertImagesResponse")]
        bool InsertImages(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/InsertImages", ReplyAction="http://tempuri.org/ICarLoanContract/InsertImagesResponse")]
        System.Threading.Tasks.Task<bool> InsertImagesAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/DeleteImages", ReplyAction="http://tempuri.org/ICarLoanContract/DeleteImagesResponse")]
        bool DeleteImages(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/DeleteImages", ReplyAction="http://tempuri.org/ICarLoanContract/DeleteImagesResponse")]
        System.Threading.Tasks.Task<bool> DeleteImagesAsync(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetImages", ReplyAction="http://tempuri.org/ICarLoanContract/GetImagesResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto[] GetImages(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetImages", ReplyAction="http://tempuri.org/ICarLoanContract/GetImagesResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto[]> GetImagesAsync(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/DelImgFalse", ReplyAction="http://tempuri.org/ICarLoanContract/DelImgFalseResponse")]
        bool DelImgFalse(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/DelImgFalse", ReplyAction="http://tempuri.org/ICarLoanContract/DelImgFalseResponse")]
        System.Threading.Tasks.Task<bool> DelImgFalseAsync(int key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetDeductList", ReplyAction="http://tempuri.org/ICarLoanContract/GetDeductListResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto[] GetDeductList(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetDeductList", ReplyAction="http://tempuri.org/ICarLoanContract/GetDeductListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto[]> GetDeductListAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/AddCarDeductProgressByKey", ReplyAction="http://tempuri.org/ICarLoanContract/AddCarDeductProgressByKeyResponse")]
        bool AddCarDeductProgressByKey(string[] idAndPeriods, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/AddCarDeductProgressByKey", ReplyAction="http://tempuri.org/ICarLoanContract/AddCarDeductProgressByKeyResponse")]
        System.Threading.Tasks.Task<bool> AddCarDeductProgressByKeyAsync(string[] idAndPeriods, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/AddCarDeductProgressOne", ReplyAction="http://tempuri.org/ICarLoanContract/AddCarDeductProgressOneResponse")]
        bool AddCarDeductProgressOne(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto model, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/AddCarDeductProgressOne", ReplyAction="http://tempuri.org/ICarLoanContract/AddCarDeductProgressOneResponse")]
        System.Threading.Tasks.Task<bool> AddCarDeductProgressOneAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto model, int operatorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateApplyIdByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateApplyIdByOrderIdResponse")]
        bool UpdateApplyIdByOrderId(int applyId, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/UpdateApplyIdByOrderId", ReplyAction="http://tempuri.org/ICarLoanContract/UpdateApplyIdByOrderIdResponse")]
        System.Threading.Tasks.Task<bool> UpdateApplyIdByOrderIdAsync(int applyId, int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetCarFinancialExportExcleList", ReplyAction="http://tempuri.org/ICarLoanContract/GetCarFinancialExportExcleListResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleDto[] GetCarFinancialExportExcleList(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleRequest model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetCarFinancialExportExcleList", ReplyAction="http://tempuri.org/ICarLoanContract/GetCarFinancialExportExcleListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleDto[]> GetCarFinancialExportExcleListAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleRequest model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetCarLoanBatchDeductList", ReplyAction="http://tempuri.org/ICarLoanContract/GetCarLoanBatchDeductListResponse")]
        Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto[] GetCarLoanBatchDeductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarLoanContract/GetCarLoanBatchDeductList", ReplyAction="http://tempuri.org/ICarLoanContract/GetCarLoanBatchDeductListResponse")]
        System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto[]> GetCarLoanBatchDeductListAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertExhibitionReview", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertExhibitionReviewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto reviewDto;
        
        public InsertExhibitionReviewRequest() {
        }
        
        public InsertExhibitionReviewRequest(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto reviewDto) {
            this.reviewDto = reviewDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertExhibitionReviewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertExhibitionReviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool InsertExhibitionReviewResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto dto;
        
        public InsertExhibitionReviewResponse() {
        }
        
        public InsertExhibitionReviewResponse(bool InsertExhibitionReviewResult, Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto dto) {
            this.InsertExhibitionReviewResult = InsertExhibitionReviewResult;
            this.dto = dto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateExhibitionReview", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateExhibitionReviewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto reviewDto;
        
        public UpdateExhibitionReviewRequest() {
        }
        
        public UpdateExhibitionReviewRequest(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto reviewDto) {
            this.reviewDto = reviewDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateExhibitionReviewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateExhibitionReviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateExhibitionReviewResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto dto;
        
        public UpdateExhibitionReviewResponse() {
        }
        
        public UpdateExhibitionReviewResponse(bool UpdateExhibitionReviewResult, Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto dto) {
            this.UpdateExhibitionReviewResult = UpdateExhibitionReviewResult;
            this.dto = dto;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarLoanContractChannel : Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarLoanContractClient : System.ServiceModel.ClientBase<Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract>, Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract {
        
        public CarLoanContractClient() {
        }
        
        public CarLoanContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarLoanContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarLoanContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarLoanContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarUserInfoDto[] QueryUserInfoList() {
            return base.Channel.QueryUserInfoList();
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarUserInfoDto[]> QueryUserInfoListAsync() {
            return base.Channel.QueryUserInfoListAsync();
        }
        
        public Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto> GetPageCarLoanBatchDeductList(int pageNum, int pageSize) {
            return base.Channel.GetPageCarLoanBatchDeductList(pageNum, pageSize);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto>> GetPageCarLoanBatchDeductListAsync(int pageNum, int pageSize) {
            return base.Channel.GetPageCarLoanBatchDeductListAsync(pageNum, pageSize);
        }
        
        public bool UpdateOrderCollectStatus(int orderId, int collectStatus, int optId) {
            return base.Channel.UpdateOrderCollectStatus(orderId, collectStatus, optId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateOrderCollectStatusAsync(int orderId, int collectStatus, int optId) {
            return base.Channel.UpdateOrderCollectStatusAsync(orderId, collectStatus, optId);
        }
        
        public bool UpdateOrderCollectStatusBatch(int[] orderIds, int collectStatus, int optId) {
            return base.Channel.UpdateOrderCollectStatusBatch(orderIds, collectStatus, optId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateOrderCollectStatusBatchAsync(int[] orderIds, int collectStatus, int optId) {
            return base.Channel.UpdateOrderCollectStatusBatchAsync(orderIds, collectStatus, optId);
        }
        
        public Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto> SelectLoanProductOrderList(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanSearchaRequest loanSearchaRequest) {
            return base.Channel.SelectLoanProductOrderList(loanSearchaRequest);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto>> SelectLoanProductOrderListAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanSearchaRequest loanSearchaRequest) {
            return base.Channel.SelectLoanProductOrderListAsync(loanSearchaRequest);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto GetLoanProductOrderInfoByOrderId(int orderId) {
            return base.Channel.GetLoanProductOrderInfoByOrderId(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductOrderDto> GetLoanProductOrderInfoByOrderIdAsync(int orderId) {
            return base.Channel.GetLoanProductOrderInfoByOrderIdAsync(orderId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductExtensionOrderDto GetLoanProductExtensionOrderByOrderId(int orderId) {
            return base.Channel.GetLoanProductExtensionOrderByOrderId(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanProductExtensionOrderDto> GetLoanProductExtensionOrderByOrderIdAsync(int orderId) {
            return base.Channel.GetLoanProductExtensionOrderByOrderIdAsync(orderId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto[] GetRepayRemindList(string RepayIdArray) {
            return base.Channel.GetRepayRemindList(RepayIdArray);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto[]> GetRepayRemindListAsync(string RepayIdArray) {
            return base.Channel.GetRepayRemindListAsync(RepayIdArray);
        }
        
        public Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto> GetPageOverdueList(int pageNum, int pageSize, System.Nullable<bool> isLongLoan, int optId) {
            return base.Channel.GetPageOverdueList(pageNum, pageSize, isLongLoan, optId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto>> GetPageOverdueListAsync(int pageNum, int pageSize, System.Nullable<bool> isLongLoan, int optId) {
            return base.Channel.GetPageOverdueListAsync(pageNum, pageSize, isLongLoan, optId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanOrderDetailDto GetLoanProductOrderDetail(int orderId) {
            return base.Channel.GetLoanProductOrderDetail(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanOrderDetailDto> GetLoanProductOrderDetailAsync(int orderId) {
            return base.Channel.GetLoanProductOrderDetailAsync(orderId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto GetLoanProductOrderSingleById(int orderId) {
            return base.Channel.GetLoanProductOrderSingleById(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto> GetLoanProductOrderSingleByIdAsync(int orderId) {
            return base.Channel.GetLoanProductOrderSingleByIdAsync(orderId);
        }
        
        public bool UpdateLoanProductOrder(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto orderDto) {
            return base.Channel.UpdateLoanProductOrder(orderDto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateLoanProductOrderAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanOrderDto orderDto) {
            return base.Channel.UpdateLoanProductOrderAsync(orderDto);
        }
        
        public bool EditLoanOrderReminderByOrderId(int orderId, int deptOptId) {
            return base.Channel.EditLoanOrderReminderByOrderId(orderId, deptOptId);
        }
        
        public System.Threading.Tasks.Task<bool> EditLoanOrderReminderByOrderIdAsync(int orderId, int deptOptId) {
            return base.Channel.EditLoanOrderReminderByOrderIdAsync(orderId, deptOptId);
        }
        
        public Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto> GetPageDeductApprovalList(int pageNum, int pageSize, int[] keyList) {
            return base.Channel.GetPageDeductApprovalList(pageNum, pageSize, keyList);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueListDto>> GetPageDeductApprovalListAsync(int pageNum, int pageSize, int[] keyList) {
            return base.Channel.GetPageDeductApprovalListAsync(pageNum, pageSize, keyList);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueExcelDto[] GetOverdueExcelList(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.OverdueSearchRequest overdueSearchRequest) {
            return base.Channel.GetOverdueExcelList(overdueSearchRequest);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarOverdueExcelDto[]> GetOverdueExcelListAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.OverdueSearchRequest overdueSearchRequest) {
            return base.Channel.GetOverdueExcelListAsync(overdueSearchRequest);
        }
        
        public bool UpdateMonthRepayInfo(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarDeductViewModelDto dto, int operaterId) {
            return base.Channel.UpdateMonthRepayInfo(dto, operaterId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMonthRepayInfoAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarDeductViewModelDto dto, int operaterId) {
            return base.Channel.UpdateMonthRepayInfoAsync(dto, operaterId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanMonthRepayDto[] GetLoanMonthRepayInfoByOrderId(int orderId) {
            return base.Channel.GetLoanMonthRepayInfoByOrderId(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.LoanMonthRepayDto[]> GetLoanMonthRepayInfoByOrderIdAsync(int orderId) {
            return base.Channel.GetLoanMonthRepayInfoByOrderIdAsync(orderId);
        }
        
        public Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto> GetPageRepayRemindList(int pageNum, int pageSize, bool isLongLoan, int optId) {
            return base.Channel.GetPageRepayRemindList(pageNum, pageSize, isLongLoan, optId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoanGlobal.PagedList<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemindListDto>> GetPageRepayRemindListAsync(int pageNum, int pageSize, bool isLongLoan, int optId) {
            return base.Channel.GetPageRepayRemindListAsync(pageNum, pageSize, isLongLoan, optId);
        }
        
        public bool UpdateRepayRemindByRepayId(int repayId, int isRemind, int operatorId) {
            return base.Channel.UpdateRepayRemindByRepayId(repayId, isRemind, operatorId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRepayRemindByRepayIdAsync(int repayId, int isRemind, int operatorId) {
            return base.Channel.UpdateRepayRemindByRepayIdAsync(repayId, isRemind, operatorId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemidDetailDto GetCarRemindDetail(int orderId, int repayId) {
            return base.Channel.GetCarRemindDetail(orderId, repayId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarRemidDetailDto> GetCarRemindDetailAsync(int orderId, int repayId) {
            return base.Channel.GetCarRemindDetailAsync(orderId, repayId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarCountDto GetIsRemindCount(bool isLongLoan, int optId) {
            return base.Channel.GetIsRemindCount(isLongLoan, optId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarCountDto> GetIsRemindCountAsync(bool isLongLoan, int optId) {
            return base.Channel.GetIsRemindCountAsync(isLongLoan, optId);
        }
        
        public bool AddLoanExtensionApplyByDto(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanExtensionApplyDto carLoanExtensionApplyDto) {
            return base.Channel.AddLoanExtensionApplyByDto(carLoanExtensionApplyDto);
        }
        
        public System.Threading.Tasks.Task<bool> AddLoanExtensionApplyByDtoAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanExtensionApplyDto carLoanExtensionApplyDto) {
            return base.Channel.AddLoanExtensionApplyByDtoAsync(carLoanExtensionApplyDto);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto[] GetExhibitionReviewlist(System.Nullable<int> orderId) {
            return base.Channel.GetExhibitionReviewlist(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto[]> GetExhibitionReviewlistAsync(System.Nullable<int> orderId) {
            return base.Channel.GetExhibitionReviewlistAsync(orderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewResponse Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract.InsertExhibitionReview(Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewRequest request) {
            return base.Channel.InsertExhibitionReview(request);
        }
        
        public bool InsertExhibitionReview(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto reviewDto, out Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto dto) {
            Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewRequest inValue = new Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewRequest();
            inValue.reviewDto = reviewDto;
            Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewResponse retVal = ((Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract)(this)).InsertExhibitionReview(inValue);
            dto = retVal.dto;
            return retVal.InsertExhibitionReviewResult;
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewResponse> InsertExhibitionReviewAsync(Dscf.PostLoan.Web.DscfCarLoanService.InsertExhibitionReviewRequest request) {
            return base.Channel.InsertExhibitionReviewAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewResponse Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract.UpdateExhibitionReview(Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewRequest request) {
            return base.Channel.UpdateExhibitionReview(request);
        }
        
        public bool UpdateExhibitionReview(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto reviewDto, out Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ExhibitionReviewDto dto) {
            Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewRequest inValue = new Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewRequest();
            inValue.reviewDto = reviewDto;
            Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewResponse retVal = ((Dscf.PostLoan.Web.DscfCarLoanService.ICarLoanContract)(this)).UpdateExhibitionReview(inValue);
            dto = retVal.dto;
            return retVal.UpdateExhibitionReviewResult;
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewResponse> UpdateExhibitionReviewAsync(Dscf.PostLoan.Web.DscfCarLoanService.UpdateExhibitionReviewRequest request) {
            return base.Channel.UpdateExhibitionReviewAsync(request);
        }
        
        public bool InsertImages(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto dto) {
            return base.Channel.InsertImages(dto);
        }
        
        public System.Threading.Tasks.Task<bool> InsertImagesAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto dto) {
            return base.Channel.InsertImagesAsync(dto);
        }
        
        public bool DeleteImages(int key) {
            return base.Channel.DeleteImages(key);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteImagesAsync(int key) {
            return base.Channel.DeleteImagesAsync(key);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto[] GetImages(int key) {
            return base.Channel.GetImages(key);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.ImagesDto[]> GetImagesAsync(int key) {
            return base.Channel.GetImagesAsync(key);
        }
        
        public bool DelImgFalse(int key) {
            return base.Channel.DelImgFalse(key);
        }
        
        public System.Threading.Tasks.Task<bool> DelImgFalseAsync(int key) {
            return base.Channel.DelImgFalseAsync(key);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto[] GetDeductList(int orderId) {
            return base.Channel.GetDeductList(orderId);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto[]> GetDeductListAsync(int orderId) {
            return base.Channel.GetDeductListAsync(orderId);
        }
        
        public bool AddCarDeductProgressByKey(string[] idAndPeriods, int operatorId) {
            return base.Channel.AddCarDeductProgressByKey(idAndPeriods, operatorId);
        }
        
        public System.Threading.Tasks.Task<bool> AddCarDeductProgressByKeyAsync(string[] idAndPeriods, int operatorId) {
            return base.Channel.AddCarDeductProgressByKeyAsync(idAndPeriods, operatorId);
        }
        
        public bool AddCarDeductProgressOne(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto model, int operatorId) {
            return base.Channel.AddCarDeductProgressOne(model, operatorId);
        }
        
        public System.Threading.Tasks.Task<bool> AddCarDeductProgressOneAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.DeductProgressDto model, int operatorId) {
            return base.Channel.AddCarDeductProgressOneAsync(model, operatorId);
        }
        
        public bool UpdateApplyIdByOrderId(int applyId, int orderId) {
            return base.Channel.UpdateApplyIdByOrderId(applyId, orderId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateApplyIdByOrderIdAsync(int applyId, int orderId) {
            return base.Channel.UpdateApplyIdByOrderIdAsync(applyId, orderId);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleDto[] GetCarFinancialExportExcleList(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleRequest model) {
            return base.Channel.GetCarFinancialExportExcleList(model);
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleDto[]> GetCarFinancialExportExcleListAsync(Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarFinancialExportExcleRequest model) {
            return base.Channel.GetCarFinancialExportExcleListAsync(model);
        }
        
        public Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto[] GetCarLoanBatchDeductList() {
            return base.Channel.GetCarLoanBatchDeductList();
        }
        
        public System.Threading.Tasks.Task<Dscf.PostLoan.CarLoanBLL.DscfCarLoanService.CarLoanBatchDeductDto[]> GetCarLoanBatchDeductListAsync() {
            return base.Channel.GetCarLoanBatchDeductListAsync();
        }
    }
}
